notifications:
  email:
    on_success: never
    on_failure: always

sudo: required
dist: trusty

language: c
compiler: gcc

addons:
  apt:
    packages:
      - libgpgme11-dev
      - libnotmuch-dev
      - libtokyocabinet-dev
      - libgdbm-dev
      - libdb-dev
#     - libslang2-dev
#     - libqdbm-dev

env:
    # Default config
  - OPTS=""
  - OPTS="--enable-sidebar"

before_script:
  - autoreconf -i

script:
  - ./configure $OPTS
  - make
  - ./mutt -v

